export default defineEventHandler(() => {
  return [
    {
      cityName: 'Sydney',
      address: '1 Oxford St, Darlinghurst NSW 2010, Australia',
      image: 'sydney.webp',
      customers: 545,
      averageRating: 4.7,
    },
    {
      cityName: 'New York',
      address: '350 Fifth Avenue New York, NY 10118, United States',
      image: 'newyork.webp',
      customers: 465,
      averageRating: 4.9,
    },
    {
      cityName: 'Rio de Janeiro',
      address: 'Av. Atlântica, 1702 - Copacabana, Rio de Janeiro - RJ, 22021-001, Brazil',
      image: 'riodejaneiro.webp',
      customers: 311,
      averageRating: 4.3,
    },
    {
      cityName: 'Tokyo',
      address: '1 Chome-1-2 Oshiage, Sumida City, Tokyo 131-0045, Japan',
      image: 'tokyo.webp',
      customers: 628,
      averageRating: 4.8,
    },
    {
      cityName: 'Cairo',
      address:
        'Great Pyramid of Giza, Al Haram, Nazlet El-Semman, Al Haram, Giza Governorate, Egypt',
      image: 'cairo.webp',
      customers: 254,
      averageRating: 4.5,
    },
    {
      cityName: 'Barcelona',
      address: 'Plaça de la Sagrada Família, s/n, 08013 Barcelona, Spain',
      image: 'barcelona.webp',
      customers: 409,
      averageRating: 4.7,
    },
    {
      cityName: 'Sarajevo',
      address: 'Obala Isa-bega Ishakovica 3, Sarajevo 71000, Bosnia and Herzegovina',
      image: 'sarajevo.webp',
      customers: 584,
      averageRating: 4.6,
    },
    {
      cityName: 'Paris',
      address: 'Champ de Mars, 5 Avenue Anatole France, 75007 Paris, France',
      image: 'paris.webp',
      customers: 693,
      averageRating: 4.9,
    },
    {
      cityName: 'Johannesburg',
      address: '301 9th St, Johannesburg 2094, South Africa',
      image: 'johannesburg.webp',
      customers: 316,
      averageRating: 4.4,
    },
    {
      cityName: 'London',
      address: '10 Downing Street, Westminster, London SW1A 2AA, United Kingdom',
      image: 'london.webp',
      customers: 720,
      averageRating: 4.9,
    },
    {
      cityName: 'Berlin',
      address: 'Brandenburg Gate, Pariser Platz, 10117 Berlin, Germany',
      image: 'berlin.webp',
      customers: 530,
      averageRating: 4.7,
    },
    {
      cityName: 'Rome',
      address: 'Colosseum, Piazza del Colosseo, 1, 00184 Rome, Italy',
      image: 'rome.webp',
      customers: 610,
      averageRating: 4.8,
    },
    {
      cityName: 'Amsterdam',
      address: 'Dam Square, 1012 Amsterdam, Netherlands',
      image: 'amsterdam.webp',
      customers: 590,
      averageRating: 4.7,
    },
    {
      cityName: 'Mumbai',
      address: 'Gateway of India, Apollo Bandar, Colaba, Mumbai, Maharashtra 400001, India',
      image: 'mumbai.webp',
      customers: 490,
      averageRating: 4.5,
    },
    {
      cityName: 'Beijing',
      address: 'Tiananmen Square, Dongcheng, Beijing, China',
      image: 'beijing.webp',
      customers: 540,
      averageRating: 4.6,
    },
    {
      cityName: 'Dubai',
      address: 'Burj Khalifa, 1 Sheikh Mohammed bin Rashid Blvd, Dubai, United Arab Emirates',
      image: 'dubai.webp',
      customers: 670,
      averageRating: 4.8,
    },
    {
      cityName: 'Toronto',
      address: 'CN Tower, 301 Front St W, Toronto, ON M5V 2T6, Canada',
      image: 'toronto.webp',
      customers: 580,
      averageRating: 4.7,
    },
    {
      cityName: 'São Paulo',
      address: 'Paulista Avenue, Bela Vista, São Paulo - SP, 01310-100, Brazil',
      image: 'saopaulo.webp',
      customers: 400,
      averageRating: 4.4,
    },
    {
      cityName: 'Istanbul',
      address: 'Hagia Sophia, Sultan Ahmet, Istanbul, Turkey',
      image: 'istanbul.webp',
      customers: 550,
      averageRating: 4.7,
    },
    {
      cityName: 'Bangkok',
      address: 'Wat Arun, 158 Thanon Wang Doem, Wat Arun, Bangkok Yai, Bangkok 10600, Thailand',
      image: 'bangkok.webp',
      customers: 680,
      averageRating: 4.9,
    },
    {
      cityName: 'Cape Town',
      address: 'Table Mountain National Park, Cape Town, South Africa',
      image: 'capetown.webp',
      customers: 380,
      averageRating: 4.3,
    },
    {
      cityName: 'Stockholm',
      address: 'Gamla Stan, Stockholm, Sweden',
      image: 'stockholm.webp',
      customers: 510,
      averageRating: 4.6,
    },
    {
      cityName: 'Seoul',
      address: 'Gyeongbokgung Palace, 161 Sajik-ro, Jongno-gu, Seoul, South Korea',
      image: 'seoul.webp',
      customers: 640,
      averageRating: 4.8,
    },
    {
      cityName: 'Mexico City',
      address: 'Zócalo, Plaza de la Constitución S/N, Centro Histórico de la Cdad. de México',
      image: 'mexicocity.webp',
      customers: 440,
      averageRating: 4.5,
    },
  ];
});
